name: "[DEV] Build and Publish iOS"
    
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Bootstrap
    runs-on: macos-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 2.9.0
      # Install your project's dependencies
    - run: flutter pub get

      # Build and sign the ipa using a single flutter command
    - name: Building IPA
      run: flutter build ipa --release
          
      # Collect the file and upload as artifact         
    - name: collect ipa artifacts
      uses: actions/upload-artifact@v4
      with:
         name: release-ipa
         # Path to the release files
         path: build/ios/ipa/*.ipa


  # Release job, upload the ipa to Firebase App Distribution
  release:
    name: Release ipa to Firebase
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    
    # Retrieve ipa file from GitHub artifacts
    - uses: actions/checkout@v2
    - name: Get release-ipa from artifacts
      uses: actions/download-artifact@v2
      with:
        name: release-ipa
